---
- name: Website | Provision webservers | AWS | EC2 | Search for Ubuntu AMI
  ec2_ami_search:
    region: "{{ vpc_region }}"
    distro: "{{ linux_distribution }}"
    release: "{{ ubuntu_release }}"
    store: "{{ ami_store }}"
    virt: "{{ virutalization_type }}"
    arch: "{{ cpu_architecture }}"
  register: image_id